report/routes.py
import json
import os

from flask import (
    Blueprint, render_template,
    request, current_app,
    session, redirect, url_for
)

from access import group_required
from cache.wrapper import fetch_from_cache
from database.operations import select, call_procedure
from database.sql_provider import SQLProvider

blueprint_report = Blueprint(
    'blueprint_report',
    __name__,
    template_folder='templates',
    static_folder='static'
)

provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@blueprint_report.route('/', methods=['GET'])
@group_required
def index():
    db_config = current_app.config['db_config']
    cache_config = current_app.config['cache_config']
    cached_func = fetch_from_cache('all_reports', cache_config)(select)

    sql = provider.get('get_all_reports.sql')
    result = cached_func(db_config, sql)

    session['reports'] = {row['proc_name']: json.loads(row['data']) for row in result}
    access_list = current_app.config['access_config'].get(session.get('user_group'), [])

    return render_template('report/index.html',
                           reports=session['reports'],
                           access_list=access_list)


@blueprint_report.route('/<report_id>/create', methods=['GET', 'POST'])
@group_required
def report_create(report_id):
    if not (session.get('reports', None) and session['reports'].get(report_id, None)):
        return redirect(url_for('blueprint_report.index'))

    db_config = current_app.config['db_config']

    if request.method == 'GET':
        parameters = session['reports'][report_id]['parameters']

        return render_template('report/input_form.html',
                               title='Создание отчета',
                               report_id=report_id,
                               parameters=parameters)
    else:
        parameters = session['reports'][report_id]['parameters']
        form = {key: request.form.get(key, None) for key in parameters.keys()}
        table = session['reports'][report_id]['table']
        sql = provider.get(table + '.sql', **form)
        result = select(db_config, sql)

        print(result)

        if result:
            return render_template('report/input_form.html',
                                   title='Создание отчета',
                                   report_id=report_id, parameters=parameters,
                                   error='Отчет уже существует')

        args = list(form.values())
        result = call_procedure(db_config, report_id, *args)

        if not result:
            return render_template('report/input_form.html',
                                   title='Создание отчета',
                                   report_id=report_id, parameters=parameters,
                                   error='Отчет не может быть создан')

        table = session['reports'][report_id]['table']
        sql = provider.get(table + '.sql', **form)
        result = select(db_config, sql)

        return render_template('report/dynamic.html',
                               name=session['reports'][report_id]['name'],
                               report_id=report_id, table_items=result,
                               back_site=request.endpoint)


@blueprint_report.route('/<report_id>/view', methods=['GET', 'POST'])
@group_required
def report_view(report_id):
    if not (session.get('reports', None) and session['reports'].get(report_id, None)):
        return redirect(url_for('blueprint_report.index'))

    db_config = current_app.config['db_config']

    if request.method == 'GET':
        parameters = session['reports'][report_id]['parameters']

        return render_template('report/input_form.html',
                               title='Просмотр отчета',
                               report_id=report_id,
                               parameters=parameters)
    else:
        parameters = session['reports'][report_id]['parameters']
        form = {key: request.form.get(key, None) for key in parameters.keys()}

        table = session['reports'][report_id]['table']
        sql = provider.get(table + '.sql', **form)
        result = select(db_config, sql)

        if not result:
            return render_template('report/input_form.html',
                                   report_id=report_id, parameters=parameters,
                                   error='Отчета с заданными параметрами не существует')

        return render_template('report/dynamic.html',
                               name=session['reports'][report_id]['name'],
                               report_id=report_id, table_items=result,
                               back_site=request.endpoint)

report/templates/report/dynamic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Просмотр отчета</title>
    <link href="{{ url_for('static', filename='static.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet" type="text/css"/>
</head>
<body style="background: #2C3959">
<div class="modal-dialog" style="width: 750px">
    <div class="modal-content col-auto">
        <div class="modal-header">
            <h2>{{ name }}</h2>
        </div>
        <div class="modal-body">
            {% if table_items %}
            <table class="table table-bordered">
                <thead>
                <tr>
                    {% for column_name in table_items[0].keys() %}
                        <th scope="col">{{ column_name }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for item in table_items %}
                    <tr>
                        {% for column_name in item.keys() %}
                            <td>{{ item[column_name] }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
                <h1>NOT RESPONSE</h1>
            {% endif %}
        </div>
        <div class="modal-footer">
            <form action="{{ url_for(back_site, report_id=report_id) }}">
                <button class="btn btn-outline-dark">Вернуться назад</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

report/templates/report/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Работа с отчетами</title>
    <link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet" type="text/css"/>
</head>
<body style="background: #2C3959">
<center>
    <div class="modal-dialog">
        <div class="modal-content" style="width: 500px">
            <div class="modal-header">
                <h2> Работа с отчетами </h2>
            </div>
            <div class="modal-body">
                {% for report_id in reports.keys() %}
                    <form id="create.{{ report_id }}" action="{{ url_for('blueprint_report.report_create', report_id=report_id) }}"
                          target="_self"></form>
                    <form id="view.{{ report_id }}" action="{{ url_for('blueprint_report.report_view', report_id=report_id) }}"
                          target="_self"></form>
                    <div class="row d-flex justify-content-center align-items-center">
                        <p class="col-5 text fs-5 fw-bold">{{ reports[report_id]['name'] }}</p>
                        {% if 'blueprint_report.report_create' in access_list %}
                            <button type="submit" class="btn col-3 btn-primary" style="margin: 10px" form="create.{{ report_id }}">
                                Создать
                            </button>
                        {% endif %}
                        {% if 'blueprint_report.report_view' in access_list %}
                            <button type="submit" class="btn col-3 btn-primary" style="margin: 10px;" form="view.{{ report_id }}">
                                Посмотреть
                            </button>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <form action="/" target="_self">
                    <button type="submit" class="btn btn-outline-dark">Вернуться в меню</button>
                </form>
            </div>
        </div>
    </div>
</center>
</body>
</html>

report/templates/report/input_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet" type="text/css"/>
</head>
<body style="background: #2C3959">
<div class="modal-dialog" style="width: 500px;">
    <div class="modal-content">
        <div class="modal-header">
            <div>
                <p class="text fs-3">Введите параметры</p>
            </div>
        </div>
        <form id="query" action="" method="post"></form>
        <div class="modal-body">
            {% if error %}
                <p class="text fs-3" style="color: red">{{ error }}</p>
            {% endif %}
            {% for key in parameters.keys() %}
                <label for="{{ key }}" class="d-flex aligns-items-left">{{ parameters[key]['translate'] }}</label>
                <input type="{{ parameters[key]['value'] }}" {{ parameters[key]['style'] }} class="form-control" name="{{ key }}" id="{{ key }}"
                       form="query">
            {% endfor %}
        </div>
        <div class="modal-footer">
            <form action="{{ url_for('blueprint_report.index', report_id=report_id) }}" target="_self">
                <button class="btn btn-outline-dark">Вернуться назад</button>
            </form>
            <input type="reset" class="btn btn-outline-danger" value="Очистить" form="query">
            <input type="submit" class="btn btn-primary" value="Отправить" form="query">
        </div>
    </div>
</div>
</body>
</html>